spring:
  application:
    name: ad-euraka
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

---
spring:
  application:
    name: ad-eureka
  profiles: server1
server:
  port: 8761
eureka:
  instance:
    hostname: server1
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://server2:8762/eureka/,http://server3:8763/eureka/

---
spring:
  application:
    name: ad-eureka
  profiles: server2
server:
  port: 8762
eureka:
  instance:
    hostname: server2
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://server1:8761/eureka/,http://server3:8763/eureka/

---
spring:
  application:
    name: ad-eureka
  profiles: server3
server:
  port: 8763
eureka:
  instance:
    hostname: server3
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://server1:8761/eureka/,http://server2:8762/eureka/